# Generated by Django 3.2.7 on 2021-10-17 14:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Apellido', models.CharField(max_length=50)),
                ('Edad', models.IntegerField()),
                ('Domicilio', models.CharField(max_length=70)),
                ('Telefono', models.CharField(max_length=70)),
                ('Email', models.EmailField(max_length=80)),
                ('Perfil', models.CharField(max_length=300)),
                ('Estudios_o_Títulos', models.TextField()),
                ('Conocimientos_Laborales_Previos', models.TextField()),
                ('Conocimientos_Ingles', models.CharField(choices=[('nulo', 'Nulo'), ('basico', 'Básico'), ('Avanzado', 'Avanzado')], default='Nulo', max_length=8)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
