# Generated by Django 3.2.7 on 2021-10-17 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Curriculum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='Perfil',
            field=models.TextField(),
        ),
    ]
