# Generated by Django 3.2.7 on 2021-10-17 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Curriculum', '0002_alter_cv_perfil'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cv',
            old_name='Conocimientos_Ingles',
            new_name='Conocimientos_de_Inglés',
        ),
    ]
