# Generated by Django 3.2.7 on 2021-10-20 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Curriculum', '0004_auto_20211019_2202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cv',
            old_name='Telefono',
            new_name='telefono',
        ),
    ]
