# Generated by Django 3.2.7 on 2021-10-20 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Curriculum', '0005_rename_telefono_cv_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='localidad',
            field=models.CharField(default='Lanus', max_length=20),
            preserve_default=False,
        ),
    ]
