# Generated by Django 3.2.7 on 2021-10-20 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Curriculum', '0007_auto_20211019_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='edad',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='cv',
            name='telefono',
            field=models.IntegerField(),
        ),
    ]
