# Generated by Django 3.2.7 on 2021-10-22 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Curriculum', '0008_auto_20211019_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='edad',
            field=models.PositiveIntegerField(),
        ),
    ]
